"""Build a double-clickable macOS .app bundle. No PyInstaller, no dependencies.

A .app is just a directory with a specific shape, so we assemble it directly.
The bundled executable is a tiny shell script that execs the real Python source
in place, which means:

  - the build is instant and weighs a few KB instead of a few hundred MB
  - the app always runs your current code, so editing the .py updates the app
  - there's nothing to rebuild after a change (except the icon)

Trade-off: it needs a Python 3 with Tkinter on the machine. The launcher checks
the usual locations and shows a native alert if it can't find one.

    python3 build_app.py            -> builds into ~/Applications
    python3 build_app.py --dest DIR -> builds somewhere else
"""

import argparse
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP_NAME = "Student Loan Motivator"
BUNDLE_ID = "com.studentloanmotivator.app"
VERSION = "1.0.0"
ENTRY = HERE / "StudentLoanMotivatorApp.py"

LAUNCHER = """#!/bin/sh
# Generated by build_app.py - runs the source in place.
APP_SCRIPT="{entry}"

if [ ! -f "$APP_SCRIPT" ]; then
    osascript -e 'display alert "Student Loan Motivator" message "Source file is missing:\\n{entry}"'
    exit 1
fi

for PY in {candidates}; do
    if [ -x "$PY" ]; then
        exec "$PY" "$APP_SCRIPT"
    fi
done

osascript -e 'display alert "Student Loan Motivator" message "No Python 3 found. Install it with: brew install python"'
exit 1
"""


def python_candidates() -> list[str]:
    """Preferred interpreters, current one first - GUI launches get a bare PATH."""
    found = [sys.executable]
    for path in ("/opt/homebrew/bin/python3", "/usr/local/bin/python3", "/usr/bin/python3"):
        if path not in found:
            found.append(path)
    return found


def build(dest_dir: Path) -> Path:
    icns = HERE / "icon.icns"
    if not icns.exists():
        print("icon.icns missing - generating it first")
        subprocess.run([sys.executable, str(HERE / "make_icon.py")], check=True)

    app = dest_dir / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)

    macos = app / "Contents" / "MacOS"
    resources = app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    executable = macos / "StudentLoanMotivator"
    executable.write_text(
        LAUNCHER.format(
            entry=ENTRY,
            candidates=" ".join(f'"{p}"' for p in python_candidates()),
        )
    )
    executable.chmod(0o755)

    shutil.copy2(icns, resources / "icon.icns")

    plist = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": "StudentLoanMotivator",
        "CFBundleIconFile": "icon",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
        "LSApplicationCategoryType": "public.app-category.finance",
        "NSHumanReadableCopyright": "",
    }
    with (app / "Contents" / "Info.plist").open("wb") as handle:
        plistlib.dump(plist, handle)

    # Nudge Finder/LaunchServices to notice the new bundle and its icon.
    subprocess.run(["touch", str(app)], check=False)
    subprocess.run(
        ["/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework"
         "/Support/lsregister", "-f", str(app)],
        check=False, capture_output=True,
    )
    return app


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the macOS .app bundle")
    parser.add_argument("--dest", default=str(Path.home() / "Applications"),
                        help="where to put the bundle (default: ~/Applications)")
    args = parser.parse_args()

    dest = Path(args.dest).expanduser()
    dest.mkdir(parents=True, exist_ok=True)

    app = build(dest)
    print(f"built {app}")
    print("\nOpen it from Launchpad or Finder, then right-click its Dock icon")
    print("and choose Options > Keep in Dock.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
